import "./globals.css";
import Link from "next/link";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <head />
      <body className={inter.className}>
        <header>
          <div className="header__left">
            <Link href="/">
              <img src="/img_logo.svg" alt="로고" />
            </Link>
          </div>
          <div className="header__right">
            <img src="/img_circle.svg" alt="" />
            <div>
              <Link href="/">HOME</Link>
              <Link href="/sanggeon/story">STORY</Link>
              <Link href="/sanggeon/portfolio">Portfolio</Link>
              <Link href="">contact</Link>
              <Link href="">SIGN IN</Link>
            </div>
            <img src="/img_circle.svg" alt="" />
          </div>
        </header>
        <div className="s__container">
          <div className="s__contents">{children}</div>
          <footer>
            <p>copyright 2024. sanggeon. all rights reserved.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
